### PR TITLE
Added for the webapp section the configuration of Render App for Angular

### PR DESCRIPTION
**Pull request by Til0r**

### CODE REVIEW

**Comment by matschik** [comment]
The snippet must exactly match other examples like in React or Svelte.
For example:
- No CSS file
- Text content must be "Hello world"
- ...

**Comment by matschik** [comment]
Please take a closer look to make it very similar snippet to existing ones.
The HTML file is not matching other framework snippets. Svelte example: https://github.com/matschik/component-party/blob/main/content/7-webapp-features/1-render-app/svelte/index.html

**Comment by matschik** [comment]
There are too many mistakes... Please test this code, you'll find out it does not work.

**Comment by Til0r** [comment]
Hi @matschik, here ([https://stackblitz.com/edit/render-app?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Findex.html](https://stackblitz.com/edit/render-app?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Findex.html)) you can find a repository with the project and it seems that there is no problem, tell me more about the problems you are getting 😄

**Comment by matschik** [comment]
@Til0r I got a blank page in the Stackblitz preview.

**Comment by Til0r** [comment]
@matschik for me it works correctly both on stackblitz (as you see from the screenshot), and also downloaded and started locally

Screenshot 2023-02-14 at 00 26 54

**Comment by Til0r** [comment]
@matschik any updates?

**Comment by matschik** [comment]
Fixed by #178

**Pull request closed without merging**
