### PR TITLE
adding mithril

### PR DESCRIPTION
**Pull request by boazblake**

### CODE REVIEW

**Comment by boazblake** [comment]
@matschik should be good to go now

**Comment by boazblake** [comment]
@matschik How do I get this branch merged in?

**Comment by boazblake** [comment]
@matschik You there?

**Comment by matschik** [comment]
@boazblake I'll merge it very soon. I need to make some changes to the framework navigation bar UI. Actually there are too much frameworks in there.
I wonder what are the good use-cases where mithril makes sense compared to most popular frameworks like React, Vue, Angular, Svelte for example ?

**Comment by boazblake** [comment]
Hey @matschik !

Lots of good reasons!

Lower developer cognitive load at the fraction of JS size for two... 

Check out the official docs af to some more reasons https://mithril.js.org/framework-comparison.html

And here are some more by a fellow mithril developer https://github.com/pdfernhout/choose-mithril

**Comment by matschik** [comment]
All good ! Thanks for your contribution 🙏 
Sorry for the late merge

**Pull request merged**
