### PR TITLE
Svelte: More idiomatic "emit to parent"

### PR DESCRIPTION
**Pull request by brunnerh**
You would usually not export callbacks, Svelte has its own way of dispatching custom events.
Also, the functions to set a flag are a waste of space and not required in Svelte either.

### CODE REVIEW

**Comment by matschik** [comment]
I used event dispatcher at first and then I merged this recent PR: https://github.com/matschik/component-party.dev/pull/170
Read the discussion and this comment: https://github.com/sveltejs/svelte/issues/2323#issuecomment-569954265

What do you think ?

**Comment by brunnerh** [comment]
This is the idiomatic way of dispatching events; it keeps data and events separate and conforms to how regular DOM events work.

(It also scales better as you only need one dispatcher for arbitrarily many events and additionally allows easy event forwarding.)

**Comment by matschik** [comment]
Since it conforms to how regular DOM events, I'm good with it.
Can you conform with how functions are declared like in other framework examples ? See React or Vue examples

**Comment by brunnerh** [comment]
You mean restore `onAnswerNo`/`Yes`?

**Comment by matschik** [comment]
Look at React, Vue examples

**Comment by brunnerh** [comment]
Functions are restored.

**Pull request merged**
