### PR TITLE
refactor: :recycle: Add simpler way of passing functions to children in svelte

### PR DESCRIPTION
**Pull request by SeyyedKhandon**
Add more readable version of passing functions to children:

```html
<script>
        export let onYes;
	export let onNo;
</script>

<button on:click={onYes}> YES </button>
<button on:click={onNo}> NO </button>
```

### CODE REVIEW

**Comment by matschik** [comment]
Thanks for your contribution ! Can you just format your code with Prettier in your PR's ?

**Comment by SeyyedKhandon** [comment]
@matschik Your welcome, it's done.
There is another one which is fixing a bug:

**Comment by matschik** [comment]
You can remove the alternative way to have a clean snippet.
I approve this way of using props since I read this: https://github.com/sveltejs/svelte/issues/2323#issuecomment-569954265

**Comment by matschik** [comment]
Thanks for your contribution 🙏

**Comment by SeyyedKhandon** [comment]
Your welcome. Thank you too for this very useful project. keep up the good work buddy🎉

**Pull request merged**
